### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by sergey-morenets** [BrynCooke/cdi-unit#120]
Hi

Do you have any plans to support upcoming Java 9 release?
I tested Cdi-Unit 4.0 with the latest JDK ea build 181 and still got an exception:

java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader

	at org.jglue.cdiunit.internal.WeldTestUrlDeployment.populateCdiClasspathSet(WeldTestUrlDeployment.java:398)
	at org.jglue.cdiunit.internal.WeldTestUrlDeployment.<init>(WeldTestUrlDeployment.java:97)
	at org.jglue.cdiunit.internal.Weld11TestUrlDeployment.<init>(Weld11TestUrlDeployment.java:28)
	at org.jglue.cdiunit.CdiRunner$1.createDeployment(CdiRunner.java:106)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:764)
	at org.jglue.cdiunit.CdiRunner.createTest(CdiRunner.java:126)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.jglue.cdiunit.CdiRunner.methodBlock(CdiRunner.java:176)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

**Comment by seanf** [comment]
I don't think anyone's really looked at it yet, but the class WeldTestUrlDeployment is trying to find the directory entries on the classpath, using some assumptions about the standard Java ClassLoaders, which are no longer true in Java 9.

This looks relevant: https://stackoverflow.com/a/45612376/14379 In fact, if Luke Hutchison solves the Java 9 problem (https://github.com/lukehutch/fast-classpath-scanner/issues/36), it might be best to outsource this sort of thing to FastClasspathScanner: https://github.com/lukehutch/fast-classpath-scanner/wiki/1.-Usage#listing-classpath-elements

We will also need to configure Travis to include Java 9 combinations in the build matrix.

**Comment by seanf** [comment]
@sergey-morenets Please take a look at #125 if you've got time.

**Comment by sergey-morenets** [comment]
@seanf  Hi Sean. Thank you for new release, It works fine with JDK 9.0.1

**Comment by seanf** [comment]
Thanks @sergey-morenets. #125 merged. Closing this issue.
