### ISSUE TITLE
cdi-unit incompatible with weld 3.0.1.Final

### ISSUE THREAD

**Issue by NiklasMehner** [BrynCooke/cdi-unit#126]
When using cdi-unit with weld 3.0.1 and `@InRequestScope` test fail with:

```
org.jboss.weld.exceptions.DeploymentException: 
WELD-001408: Unsatisfied dependencies for type ConversationContext with qualifiers @Http
  at injection point [BackedAnnotatedField] @Inject @Http private org.jglue.cdiunit.ContextController.conversationContext
  at org.jglue.cdiunit.ContextController.conversationContext(ContextController.java:0)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - WELD%AbstractBuiltInBean%cdi-unitc33235b4-ed9f-406a-8fa5-e33eca0ad7a8%BoundConversationContext

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:287)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:140)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:161)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:63)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The test works using weld 2.4.5:

```java
import org.jglue.cdiunit.CdiRunner;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(CdiRunner.class)
public class ExampleTest {

	@Test
	public void test() throws Exception {
	}

}
```

**Comment by seanf** [comment]
@NiklasMehner That test doesn't seem to be using `@InRequestScope`. Which version of cdi-unit are you using?

**Comment by NiklasMehner** [comment]
I actually realized when reducing the test case to the absolute minimum, that this happens always, regardless of using @InRequestScope or not. I should have modified the description.

I am using cdi-unit 4.0.1 as maven dependency:

			<dependency>
				<groupId>org.jglue.cdi-unit</groupId>
				<artifactId>cdi-unit</artifactId>
				<version>4.0.1</version>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>org.jboss.weld.se</groupId>
				<artifactId>weld-se-core</artifactId>
				
				<version>2.4.5.Final</version>
				<scope>test</scope>
			</dependency>

**Comment by NiklasMehner** [comment]
[cdiunit.zip](https://github.com/BrynCooke/cdi-unit/files/1413738/cdiunit.zip)

Actually this seems to happen only, when the javax.servlet-api is on the classpath. I have attached a small maven project reproducing the problem.

**Comment by mortht** [comment]
As workaround you can provide a mock for the missing ConversationContext

`@RunWith(CdiRunner.class)
public class WorkaroundTest {

    @Produces @Http
    @Mock
    ConversationContext conversationContext;
}`

**Comment by seanf** [comment]
Thanks for the minimal test case. This can be fixed by adding `weld-web` to the `test` classpath.

I have updated the quickstart instructions: http://bryncooke.github.io/cdi-unit/#quickstart
and the changelog for 4.0: http://bryncooke.github.io/cdi-unit/#changelog

Thanks for the bug report.

**Comment by vanta** [comment]
Any update here? I faced the same issue with `Weld` version `3.0.1` and `cdi-unit:4.1.0`.
