### ISSUE TITLE
Using org.reflections Bug in 3.1.1

### ISSUE THREAD

**Issue by PeterProbst** [BrynCooke/cdi-unit#65]
Version 3.1.1 is using org.reflections in Version 0.9.9-RC1
In WeldTestUrlDeployment emerges the following Exeption:
java.lang.NoSuchMethodError: org.reflections.Store.get(Ljava/lang/String;)Lcom/google/common/collect/Multimap;
	at org.jglue.cdiunit.internal.WeldTestUrlDeployment.<init>(WeldTestUrlDeployment.java:226)
	at org.jglue.cdiunit.internal.Weld11TestUrlDeployment.<init>(Weld11TestUrlDeployment.java:28)
	at org.jglue.cdiunit.CdiRunner$1.createDeployment(CdiRunner.java:94)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:127)
	at org.jglue.cdiunit.CdiRunner.createTest(CdiRunner.java:114)
	at ....
In Version 3.1.2-SNAPSHOT problem is solved because of org.reflections 0.9.9-RC2
Please can you either fix this in 3.1.1 or release 3.1.2
Thank you, Peter

**Comment by BrynCooke** [comment]
3.1.1 Already uses 0.9.9-RC2
See
https://repo1.maven.org/maven2/org/jglue/cdi-unit/cdi-unit/3.1.1/cdi-unit-3.1.1.pom

**Comment by PeterProbst** [comment]
Hello Bryn,
sorry for disturbance. I have found a dependency in our maven stack on 0.9.9-RC1. So this is our fault.
So closing the topic.
