### ISSUE TITLE
Problem resolving bean from producer method in separate module using Maven

### ISSUE THREAD

**Issue by thomasandersen77** [BrynCooke/cdi-unit#69]
Hi,

I am having trouble with injection of bean when running from Maven but *not* from IntelliJ.

It is a multi-module Maven project and I have a producer in a module which my "main" module depends on. To illustrate: (Module1_with_test -> depends on-> Module2_with_producer) :)

This happened after a refactor. When everything was in the Module1 it work as expected with Maven as well, so I suspected classpath issues. The @AdditionalClasspaths did not work (if used correctly)

I am using version 3.1.0 of cdi-unit
This is my test-class:
      
    import javax.inject.Inject;
 
    @RunWith(CdiRunner.class)
    @AdditionalClasses(ConfiguredObjectMapperProducer.class)
    @AdditionalClasspaths({ConfiguredObjectMapper.class , ConfiguredObjectMapperProducer.class,     ObjectMapper.class})
    public class JacksonJsonSerializationTest {

    @Inject
    @ConfiguredObjectMapper
    ObjectMapper mapper;

    @Test
    public void testInntektJsonRoundTrip() throws Exception {
        Inntekt inntekt = new Inntekt();
        inntekt.addInntektPost(new InntektPost(Inntekt.Type.LONN, 1000));
        inntekt.addInntektPost(new InntektPost(Inntekt.Type.ARV, 2000));
        String inntekAsJson = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(inntekt);
        System.out.println(inntekAsJson);
        Inntekt inntektFromJson = mapper.readValue(inntekAsJson, Inntekt.class);
        assertThat(inntektFromJson).isNotNull();
    }

Here is the stacktrace:

    testInntektJsonRoundTrip(no.context.security.json..JacksonJsonSerializationTest)  Time elapsed: 0     sec  <<< ERROR!
    org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type     ObjectMapper with qualifiers @ConfiguredObjectMapper
      at injection point [UnbackedAnnotatedField] @Inject @ConfiguredObjectMapper no.husbanken.est.context.security.json.JacksonJsonSerializationTest.mapper
      at     no.context.security.json.JacksonJsonSerializationTest.mapper(JacksonJsonSerializationTest.java:0)

    	at     org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:368)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:289)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:135)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:166)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:514)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

 

Any help on this issue would be helpful.

**Comment by thomasandersen77** [comment]
This was resolved by adding a beans.xml in Module2. I was a bit quick to report this as an issue.

**Comment by capprice** [comment]
Hello, CDI 1.2 introduced the concept of an implicit bean archive.
You no longer need a beans.xml as long as your classes are annotated with bean defining annotations.

However this does not work with Cdirunner. You still need a beans.xml.
As it stands now we need to add this file not for production purposes but only so that tests run.
Would be nice this part worked like defined in the spec.
