### ISSUE TITLE
CDIUnit stops working with weld 2.2.10.Final+

### ISSUE THREAD

**Issue by oliverwolff** [BrynCooke/cdi-unit#72]
While with weld 2.2.9.final everything worked fine, we ran into problems while trying to upgrade to 2.2.10.Final, and  2.2.12.Final. The only change we did is the upgrade. Simplified example
...
@RunWith(CdiRunner.class)
public class CDIUnitSampleTest {
    
    @Test
    public void someTestStuff() {
        assertNotNull(new Object());
    }
}
...
Will fail with stacktrace
...
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type WeldListener with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.jglue.cdiunit.ContextController.listener
  at org.jglue.cdiunit.ContextController.listener(ContextController.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

...

**Comment by beihaifeiwu** [comment]
+1

**Comment by ohlsen3000** [comment]
+1

**Comment by BrynCooke** [comment]
Please try 3.1.3

**Comment by ohlsen3000** [comment]
Works like a charm. Thanks so much!
